              
<a href="http://192.168.31.226/">
    <img src="<?php echo $this->getViewFileUrl('images/logo-big.png') ?>" /> 

</a>  

<div class="footer__contact-rating">
    <h2>Reviews</h2>
    <ul class="footer__contact-star-list">
        <li class="footer__contact-star-item">
            <img src="<?php echo $this->getViewFileUrl('images/star.png') ?>" /> 
        </li>
        <li class="footer__contact-star-item">
            <img src="<?php echo $this->getViewFileUrl('images/star.png') ?>" />   
        </li>
        <li class="footer__contact-star-item">
            <img src="<?php echo $this->getViewFileUrl('images/star.png') ?>" />   
        </li>
        <li class="footer__contact-star-item">
            <img src="<?php echo $this->getViewFileUrl('images/star.png') ?>" />   
        </li>
         <li class="footer__contact-star-item">
            <img src="<?php echo $this->getViewFileUrl('images/star.png') ?>" />   
        </li>                     
    </ul>
    <p class="footer__contact-rating-point">4.7</p>
</div>
<div class="footer__social">
    <a href="https://www.facebook.com/GLAMIRA.co.uk" class="footer__social-link">
        <img src="<?php echo $this->getViewFileUrl('images/fb.png') ?>" />    
    </a>
    <a href="https://twitter.com/Glamira_Diamond/" class="footer__social-link">
        <img src="<?php echo $this->getViewFileUrl('images/twitter.png') ?>" /> 

    </a>
    <a href="https://www.instagram.com/glamira/" class="footer__social-link">
        <img src="<?php echo $this->getViewFileUrl('images/insatgram.png') ?>" /> 
    </a>
</div>
