
<li class="footer__contact-badges">
    <div class="row">
        <img src="<?php echo $this->getViewFileUrl('images/ft-3.png') ?>" class="footer__contact-badges-img"/> 
        <img src="<?php echo $this->getViewFileUrl('images/ft-1.png') ?>" class="footer__contact-badges-img"/>                             
        <img src="<?php echo $this->getViewFileUrl('images/ft-2.png') ?>" class="footer__contact-badges-img"/>                             
     
    </div>
</li>
    