
<div class="footer__heading-close hide-on-mobi show-on-pc">

    </div>
    <ul class="  footer__heading-list">
        <li class="footer__heading-item">
            <img src="<?php echo $this->getViewFileUrl('images/come-back-left.png') ?>" /> 
                 60 Day Return Policy                                   
        </li>
        <li class="footer__heading-item  ">
            <img src="<?php echo $this->getViewFileUrl('images/hand.png') ?>" /> 
                Handcrafted Jewelry           
        </li>
        <li class="footer__heading-item">
            <img src="<?php echo $this->getViewFileUrl('images/guard.png') ?>" /> 
                Lifetime Warranty      
        </li>
        <li class="footer__heading-item ">
            <img src="<?php echo $this->getViewFileUrl('images/car.png') ?>" /> 
                Free Insured Shipping       
        </li>
       
    </ul>
