<ul class="footer__sponsor-list">
    <li class="footer__sponsor-item ">
        <a href="http://192.168.31.226/pay" class="footer__sponsor-item-link">
            <img src="<?php echo $this->getViewFileUrl('images/footer-1.png') ?>" class="footer__sponsor-img "/> 
            
        </a>
    </li>
    <li class="footer__sponsor-item ">
        <a href="http://192.168.31.226/pay" class="footer__sponsor-item-link">
            <img src="<?php echo $this->getViewFileUrl('images/footer-2.png') ?>" class="footer__sponsor-img "/> 
            
        </a>
    </li>
    <li class="footer__sponsor-item hide-on-pc">
        <a href="http://192.168.31.226/pay" class="footer__sponsor-item-link">
        <img src="<?php echo $this->getViewFileUrl('images/footer-3.png') ?>" class="footer__sponsor-img "/> 

        </a>
    </li>
    <li class="footer__sponsor-item hide-on-pc">
        <a href="http://192.168.31.226/pay" class="footer__sponsor-item-link">
            <img src="<?php echo $this->getViewFileUrl('images/footer-4.png') ?>" class="footer__sponsor-img "/> 
            
        </a>
    </li>
    <li class="footer__sponsor-item hide-on-pc">
        <a href="http://192.168.31.226/pay" class="footer__sponsor-item-link">
            <img src="<?php echo $this->getViewFileUrl('images/footer-5.png') ?>" class="footer__sponsor-img "/> 
            
        </a>
    </li>
    <li class="footer__sponsor-item hide-on-pc">
        <a href="http://192.168.31.226/pay" class="footer__sponsor-item-link">
            <img src="<?php echo $this->getViewFileUrl('images/footer-6.png') ?>" class="footer__sponsor-img "/> 
            
        </a>
    </li>
    <li class="footer__sponsor-item ">
        <a href="http://192.168.31.226/pay" class="footer__sponsor-item-link">
            <img src="<?php echo $this->getViewFileUrl('images/footer-7.png') ?>" class="footer__sponsor-img "/> 
            
        </a>
    </li>
    <li class="footer__sponsor-item ">
        <a href="http://192.168.31.226/pay" class="footer__sponsor-item-link">
            <img src="<?php echo $this->getViewFileUrl('images/footer-8.png') ?>" class="footer__sponsor-img "/> 
            
        </a>
    </li>
    <li class="footer__sponsor-item ">
        <a href="http://192.168.31.226/pay" class="footer__sponsor-item-link">
            <img src="<?php echo $this->getViewFileUrl('images/footer-9.png') ?>" class="footer__sponsor-img "/> 
            
        </a>
    </li>
    <li class="footer__sponsor-item ">
        <a href="http://192.168.31.226/pay" class="footer__sponsor-item-link">
            <img src="<?php echo $this->getViewFileUrl('images/footer-10.png') ?>" class="footer__sponsor-img "/> 
            
        </a>
    </li>
    <li class="footer__sponsor-item ">
        <a href="http://192.168.31.226/pay" class="footer__sponsor-item-link">
            <img src="<?php echo $this->getViewFileUrl('images/footer-11.png') ?>" class="footer__sponsor-img "/> 
            
        </a>
    </li>
</ul>
    