
<div class="footer__bottom-country ">
        <img src="<?php echo $this->getViewFileUrl('images/country.png') ?>" class="footer__bottom-country-img "/>
    </div>
    <ul class="footer__bottom-list">
        <li class="footer__bottom-item">
            <a href="http://192.168.31.226/privacy-policy-cookie-restriction-mode" class="footer__bottom-item-link">Terms &amp; Conditions</a>
        </li>
        <li class="footer__bottom-item">
            <a href="http://192.168.31.226/privacy-policy-cookie-restriction-mode" class="footer__bottom-item-link">Privacy Policy</a>
        </li>

    </ul>
    <div class="footer__bottom-year">
        Glamira 2008 - 2022
    </div>

    