
<div class="panel header">
    <!-- This markup portion is the source for Mobile View Navigation Menu -->
    <ul class="header links">
              
        <li class="customer-welcome active">
                
            <!-- Markup portion for Logged in customer -->
            <div class="customer-menu" data-target="dropdown" aria-hidden="false">
                <ul class="header links">
                    <li class="account" >
                        <a href="http://192.168.31.206/customer/account/" id="my-account">
                            My account
                            <img src="<?php echo $this->getViewFileUrl('images/acc.png'); ?>" />    
                        </a>
                    </li>
                    <li class="link wishlist" data-bind="scope: 'wishlist'">
                        <a href="http://192.168.31.206/wishlist/" id="my-wishlist">
                            <img src="<?php echo $this->getViewFileUrl('images/heart.png'); ?>" />    
                        </a>
                    </li>
                </ul>
            </div>
            <li class="link authorization-link" data-label="or">
                <a href="http://192.168.31.206/customer/account/logout/">Sign Out</a>
            </li>
        </li>
        <!-- Markup portion for Logged out customer -->
        <li class="link authorization-link" data-label="or">
            <a href="http://192.168.31.206/customer/account/login/referer/aHR0cDovLzE5Mi4xNjguMzEuMjA2Lw%2C%2C/">Sign In</a>
        </li>
        <li>
            <a href="http://192.168.31.206/customer/account/create/" id="create-account">Create an Account</a>
        </li>
    </ul>
</div>


<div id="store.links hide-on-tablet">
    <!-- Navigation Menu for Mobile View will be cloned here from the source -->
</div>