<div class="product__benefits">
    <ul class="row product__benefits-list">
        <li class="col c-2 l-2">
            <img src="<?php echo $this->getViewFileUrl('images/car2.png'); ?>"/> 
        </li>
        <li class="col c-10 l-10">
            <h3>Free delivery & return</h3>
            <p>Estimated ship: 23 Aug, 2022<br>Return Policy: 60 days</p>
            <p>View delivery options</p>
        </li>

    </ul>
    <ul class="row product__benefits-list">
        <li class="col c-2 l-2">
            <img src="<?php echo $this->getViewFileUrl('images/guard2.png'); ?>"/> 
        </li>
        <li class="col c-10 l-10">
            <h3>3 year Protection plan</h3>
            <p>Estanded: $969 <br>Estanded Plus: $1,662</p>
            <p>View delivery options</p>
        </li>

    </ul>
    <ul class="row product__benefits-list">
        <li class="col c-2 l-2">
            <img src="<?php echo $this->getViewFileUrl('images/tron.png'); ?>"/> 
        </li>
        <li class="col c-10 l-10">
            <h3>Interest-Free installments</h3>
            <p>3 mon: $923 x 3<br>6 mon: $462 x 6</p>
            <p>Read more</p>
        </li>

    </ul>
    <ul class="row product__benefits-list">
        <li class="col c-2 l-2">
            <img src="<?php echo $this->getViewFileUrl('images/qua.png'); ?>"/> 
        </li>
        <li class="col c-10 l-10">
            <h3>Order now, gift before delivery</h3>
            <p>Customize and order your product and get gift certificate today</p>
            <p>Read details</p>
        </li>

    </ul>
    
</div>