<div class="why-create-account">
    <div class="accordion-group">
        <ul class="accordion-group-list">
            <li class="accordion-group-item">
                <p class="accordion-group-title">
                <svg width="26" height="26" viewBox="0 0 26 26" fill="none" xmlns="http://www.w3.org/2000/svg"> <path d="M6.5 11.3193H14.3C17.8898 11.3193 20.8 14.2295 20.8 17.8193V17.8193" stroke="#637284"></path> <path d="M9.25772 14.0678L6.5 11.3101L9.25772 8.55234" stroke="#637284"></path> </svg> 
                    60-Day Returns
                </p>
                <p class="accordion-group-content">We are committed to your satisfaction. Engraved or non-engraved; if you are not happy with your choice, return it in original condition within 60 days.</p>
            </li>
            <li class="accordion-group-item">
                <p class="accordion-group-title">
                    <svg width="26" height="26" viewBox="0 0 26 26" fill="none" xmlns="http://www.w3.org/2000/svg"> <path d="M16.9 6.5L19.5 6.5L19.5 9.1" stroke="#637284"></path> <path d="M9.1 6.5L6.5 6.5L6.5 9.1" stroke="#637284"></path> <path d="M19.5 16.9L19.5 19.5L16.9 19.5" stroke="#637284"></path> <path d="M9.1 19.5L6.5 19.5L6.5 16.9" stroke="#637284"></path> <path d="M6.5 6.5L19.5 19.5M6.5 19.5L19.5 6.5" stroke="#637284"></path> </svg>
                    Free Resizing
                </p>
                <p class="accordion-group-content">Great things start with little details. GLAMIRA will assist you with keeping the secret of a surprise and resize your ring, one time, free of charge within the first 60 days of receipt.</p>
            </li>
            <li class="accordion-group-item">
                <p class="accordion-group-title">
                <svg width="26" height="26" viewBox="0 0 26 26" fill="none" xmlns="http://www.w3.org/2000/svg"> <path d="M13.6499 9.75L14.6815 11.5802L16.7408 11.9957L15.319 13.5423L15.5602 15.6293L13.6499 14.755L11.7396 15.6293L11.9808 13.5423L10.559 11.9957L12.6183 11.5802L13.6499 9.75Z" fill="#637284"></path> <path d="M4.3999 12.7362V5.78644C8.24495 5.63454 11.6213 3.73879 13.6499 0.903329C15.6785 3.73879 19.0548 5.63454 22.8999 5.78644V12.7362C22.8999 18.0548 19.2516 22.7862 13.6499 25.4478C8.04823 22.7862 4.3999 18.0548 4.3999 12.7362Z" stroke="#637284"></path> </svg>
                    Lifetime Warranty
                </p>
                <p class="accordion-group-content">We stand behind the quality of our jewellery and provide lifetime warranty for all of our products. Every order is made and treated with care by our experts, from the very first second. Enjoy the quality of professional masterpiece and feel confident that your unique design jewelry will last a lifetime.</p>
            </li>
            <li class="accordion-group-item">
                <p class="accordion-group-title">
                <svg width="26" height="26" viewBox="0 0 26 26" fill="none" xmlns="http://www.w3.org/2000/svg"> <path d="M13.6499 9.75L14.6815 11.5802L16.7408 11.9957L15.319 13.5423L15.5602 15.6293L13.6499 14.755L11.7396 15.6293L11.9808 13.5423L10.559 11.9957L12.6183 11.5802L13.6499 9.75Z" fill="#637284"></path> <path d="M4.3999 12.7362V5.78644C8.24495 5.63454 11.6213 3.73879 13.6499 0.903329C15.6785 3.73879 19.0548 5.63454 22.8999 5.78644V12.7362C22.8999 18.0548 19.2516 22.7862 13.6499 25.4478C8.04823 22.7862 4.3999 18.0548 4.3999 12.7362Z" stroke="#637284"></path> </svg>
                    Free Insured Shipping
                </p>
                <p class="accordion-group-content">  
                    Jewellery is delicate and requires extra care while in delivery. GLAMIRA offers complementary & insured shipping on all orders for loss or damage in transit. Once the order leaves our premises, you will be provided with a tracking number to track your delivery.  
                </p>
                <p class="accordion-group-content">  
                    We recommend you open your package, inspect the content(s) and check for damage. If you detect any damage, please file a damage claim and reject the receipt of the delivery.      
                </p>

            </li>

        </ul>

        <ul class="accordion-group-list">
            <li class="accordion-group-item">
                <p class="accordion-group-title">
                    Contact Us!
                </p>
                <p class="accordion-group-content">Our team would be happy to support and advise you!</p>
            </li>
        </ul>

    </div>
</div>


