<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**  @var $block \Magento\Checkout\Block\Cart */
?>
<div class="cart-empty">
    <?= $block->getChildHtml('checkout_cart_empty_widget') ?>
    <h2><?= $block->escapeHtml(__('Shopping Bag is Empty.')) ?></h2>
    <p><?= $block->escapeHtml(__('You have no items in your shopping cart.')) ?></p>
    <p><?= $block->escapeHtml(
        __(
            'Click <a href="%1">here</a> to continue shopping.',
            $block->escapeUrl($block->getContinueShoppingUrl())
        ),
        ['a']
    ) ?>
    </p>
    <?= $block->getChildHtml('shopping.cart.table.after') ?>
</div>
<script type="text/x-magento-init">
{
    "*": {
        "Magento_Checkout/js/empty-cart": {}
    }
}
</script>
